version: '3.7'

services:

  larawater_nginx:
    container_name: "larawater_nginx"
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    ports:
      - 80:80
    networks:
      - internal
    volumes:
      - .:/larawater/
      - ./.docker/logs/nginx:/var/log/nginx/

  larawater_mariadb:
    container_name: "larawater_mariadb"
    image: mariadb:11.0.2
    volumes:
      - ./.docker/database/${DB_DATABASE}:/var/lib/mysql/${DB_DATABASE}
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_USER: ${DB_USERNAME}
    networks:
      - internal

  larawater_php82:
    container_name: "larawater_php82"
    restart: unless-stopped
    build:
      context: .
      dockerfile: "./.docker/php/Dockerfile"
    volumes:
      - .:/larawater/
    networks:
      - internal
    depends_on:
      - larawater_nginx
      - larawater_mariadb
    command: sh -c "composer install && chmod -R 777 storage && chmod -R 777 bootstrap/cache && php artisan migrate && php-fpm"

networks:
  internal:
    driver: bridge